sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.2.1"
  - development
  
services:
  - mongodb
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib git travix https://github.com/kevinresol/travix node_patch
  - pushd "$(haxelib path travix | head -n 1)/../" &&
      haxe build.hxml &&
    popd
  - haxelib run travix install

script:
  - haxelib run travix neko
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix node
